---
- name: "{{ stage_operation }} terraform stage `{{ stage_name }}`: Setup AWS backend"
  include_tasks: setup_aws_backend.yml
  when: aws_bootstrap.enabled and terraform_backend_config is not defined

- name: "{{ stage_operation }} terraform stage `{{ stage_name }}`: Setup custom backend"
  include_tasks: setup_custom_backend.yml
  when: not aws_bootstrap.enabled and terraform_backend_config is not defined

- name: "{{ stage_operation }} terraform stage `{{ stage_name }}`"
  terraform:
    project_path: '{{ playbook_dir }}/../terraform_stages/{{ stage_name }}'
    state: '{{ state }}'
    force_init: true
#    lock: true
    variables: "{{ terraform_variables if terraform_variables is defined else '{}' }}"
    backend_config: "{{ terraform_backend_config }}"

#    variables_file: "variables/{{ environment_name }}.tfvars"
...
