aws_bootstrap:
  enabled: true
  s3_bucket: terraform-do8byeqctmumjgorb6dk4yv3
  # Optional parameters. See https://github.com/vexingcodes/terraform-aws-bootstrap
#  dynamodb: terraform
#  iam_group: terraform
#  iam_user: terraform
#  secret: terraform

# This is used only if aws_bootstrap is not enabled
terraform_backend:
  path: bootstrap.tfstate